#pragma once

#ifndef NTDDI_VERSION
#define NTDDI_VERSION 0x0A000008
#endif
#ifndef _WIN32_WINNT
#define _WIN32_WINNT 0x0A00
#endif

#include <ntddk.h>

#ifndef PROCESS_TERMINATE
#define PROCESS_TERMINATE           0x0001
#endif
#ifndef PROCESS_SUSPEND_RESUME
#define PROCESS_SUSPEND_RESUME      0x0800
#endif

// ========== 设备名 ==========

#define DEVICE_NAME    L"\\Device\\OpenSysKit"
#define SYMLINK_NAME   L"\\??\\OpenSysKit"

// ========== IOCTL 控制码 ==========

#define DEVICE_TYPE_OPENSYSKIT  0x8000

// 进程
#define IOCTL_ENUM_PROCESSES        CTL_CODE(DEVICE_TYPE_OPENSYSKIT, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KILL_PROCESS          CTL_CODE(DEVICE_TYPE_OPENSYSKIT, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_FREEZE_PROCESS        CTL_CODE(DEVICE_TYPE_OPENSYSKIT, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_UNFREEZE_PROCESS      CTL_CODE(DEVICE_TYPE_OPENSYSKIT, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PROTECT_PROCESS       CTL_CODE(DEVICE_TYPE_OPENSYSKIT, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_UNPROTECT_PROCESS     CTL_CODE(DEVICE_TYPE_OPENSYSKIT, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ELEVATE_PROCESS       CTL_CODE(DEVICE_TYPE_OPENSYSKIT, 0x807, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ENUM_MODULES          CTL_CODE(DEVICE_TYPE_OPENSYSKIT, 0x808, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_READ_PROCESS_MEMORY   CTL_CODE(DEVICE_TYPE_OPENSYSKIT, 0x809, METHOD_BUFFERED, FILE_ANY_ACCESS)  // 暂时禁用
#define IOCTL_WRITE_PROCESS_MEMORY  CTL_CODE(DEVICE_TYPE_OPENSYSKIT, 0x80A, METHOD_BUFFERED, FILE_ANY_ACCESS)  // 暂时禁用
#define IOCTL_ENUM_THREADS          CTL_CODE(DEVICE_TYPE_OPENSYSKIT, 0x80B, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_HIDE_PROCESS          CTL_CODE(DEVICE_TYPE_OPENSYSKIT, 0x80C, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_UNHIDE_PROCESS        CTL_CODE(DEVICE_TYPE_OPENSYSKIT, 0x80D, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_INJECT_DLL            CTL_CODE(DEVICE_TYPE_OPENSYSKIT, 0x80E, METHOD_BUFFERED, FILE_ANY_ACCESS)   // 暂时禁用

// 文件
#define IOCTL_DELETE_FILE           CTL_CODE(DEVICE_TYPE_OPENSYSKIT, 0x810, METHOD_BUFFERED, FILE_ANY_ACCESS)

// 内核模块
#define IOCTL_ENUM_KERNEL_MODULES   CTL_CODE(DEVICE_TYPE_OPENSYSKIT, 0x820, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_UNLOAD_DRIVER         CTL_CODE(DEVICE_TYPE_OPENSYSKIT, 0x821, METHOD_BUFFERED, FILE_ANY_ACCESS)

// 句柄
#define IOCTL_ENUM_HANDLES          CTL_CODE(DEVICE_TYPE_OPENSYSKIT, 0x830, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_CLOSE_HANDLE          CTL_CODE(DEVICE_TYPE_OPENSYSKIT, 0x831, METHOD_BUFFERED, FILE_ANY_ACCESS)

// 注册表（暂时禁用）
#define IOCTL_REG_DELETE_KEY        CTL_CODE(DEVICE_TYPE_OPENSYSKIT, 0x840, METHOD_BUFFERED, FILE_ANY_ACCESS)  // 暂时禁用
#define IOCTL_REG_DELETE_VALUE      CTL_CODE(DEVICE_TYPE_OPENSYSKIT, 0x841, METHOD_BUFFERED, FILE_ANY_ACCESS)  // 暂时禁用

// 网络
#define IOCTL_ENUM_CONNECTIONS      CTL_CODE(DEVICE_TYPE_OPENSYSKIT, 0x850, METHOD_BUFFERED, FILE_ANY_ACCESS)

// ========== 通用结构 ==========

#define PROCESS_KILL_RESULT_VERSION 1
#define PROCESS_KILL_METHOD_NONE    0
#define PROCESS_KILL_METHOD_PSP     1
#define PROCESS_KILL_METHOD_ZW      2

typedef struct _PROCESS_REQUEST {
    ULONG ProcessId;
} PROCESS_REQUEST, *PPROCESS_REQUEST;

typedef struct _PROCESS_KILL_RESULT {
    ULONG Version;
    ULONG OperationStatus;
    ULONG Method;
    ULONG Reserved;
} PROCESS_KILL_RESULT, *PPROCESS_KILL_RESULT;

typedef struct _PROCESS_INFO {
    ULONG  ProcessId;
    ULONG  ParentProcessId;
    ULONG  ThreadCount;
    SIZE_T WorkingSetSize;
    WCHAR  ImageName[260];
} PROCESS_INFO, *PPROCESS_INFO;

typedef struct _PROCESS_LIST_HEADER {
    ULONG Count;
    ULONG TotalSize;
} PROCESS_LIST_HEADER, *PPROCESS_LIST_HEADER;

typedef struct _FILE_PATH_REQUEST {
    WCHAR Path[520];
} FILE_PATH_REQUEST, *PFILE_PATH_REQUEST;

// ========== 提权级别 ==========

#define ELEVATE_LEVEL_ADMIN             0
#define ELEVATE_LEVEL_SYSTEM            1
#define ELEVATE_LEVEL_TRUSTED_INSTALLER 2
#define ELEVATE_LEVEL_STANDARD_USER     3

typedef struct _PROCESS_ELEVATE_REQUEST {
    ULONG ProcessId;
    ULONG Level;
} PROCESS_ELEVATE_REQUEST, *PPROCESS_ELEVATE_REQUEST;

// ========== 进程模块枚举 ==========

typedef struct _MODULE_INFO {
    ULONG_PTR BaseAddress;
    ULONG     SizeOfImage;
    WCHAR     FullPath[520];
    WCHAR     BaseName[260];
} MODULE_INFO, *PMODULE_INFO;

typedef struct _MODULE_LIST_HEADER {
    ULONG Count;
    ULONG TotalSize;
} MODULE_LIST_HEADER, *PMODULE_LIST_HEADER;

// ========== 进程内存读写（暂时禁用）==========

typedef struct _PROCESS_MEMORY_REQUEST {
    ULONG   ProcessId;
    ULONG64 Address;
    ULONG   Size;
} PROCESS_MEMORY_REQUEST, *PPROCESS_MEMORY_REQUEST;

#define PROCESS_MEMORY_MAX_SIZE (64 * 1024)

// ========== 线程枚举 ==========

typedef struct _THREAD_INFO {
    ULONG   ThreadId;
    ULONG   ProcessId;
    LONG    Priority;
    ULONG64 StartAddress;   // PsGetThreadWin32StartAddress
    BOOLEAN IsTerminating;
    UCHAR   Padding[3];
} THREAD_INFO, *PTHREAD_INFO;

typedef struct _THREAD_LIST_HEADER {
    ULONG Count;
    ULONG TotalSize;
} THREAD_LIST_HEADER, *PTHREAD_LIST_HEADER;

// ========== DLL 注入 ==========

typedef struct _INJECT_DLL_REQUEST {
    ULONG ProcessId;
    WCHAR DllPath[520];
} INJECT_DLL_REQUEST, *PINJECT_DLL_REQUEST;

// ========== 内核模块枚举 ==========

typedef struct _KERNEL_MODULE_INFO {
    ULONG_PTR BaseAddress;
    ULONG     SizeOfImage;
    WCHAR     FullPath[520];
    WCHAR     BaseName[64];
} KERNEL_MODULE_INFO, *PKERNEL_MODULE_INFO;

typedef struct _KERNEL_MODULE_LIST_HEADER {
    ULONG Count;
    ULONG TotalSize;
} KERNEL_MODULE_LIST_HEADER, *PKERNEL_MODULE_LIST_HEADER;

typedef struct _DRIVER_SERVICE_REQUEST {
    WCHAR ServiceName[256];
} DRIVER_SERVICE_REQUEST, *PDRIVER_SERVICE_REQUEST;

// ========== 句柄枚举 ==========

typedef struct _HANDLE_ENUM_REQUEST {
    ULONG ProcessId;    // 0 = 枚举全系统
} HANDLE_ENUM_REQUEST, *PHANDLE_ENUM_REQUEST;

typedef struct _HANDLE_INFO {
    ULONG     ProcessId;
    ULONG64   Handle;
    ULONG     ObjectTypeIndex;
    ULONG     GrantedAccess;
    ULONG64   ObjectAddress;
    WCHAR     TypeName[64];
    WCHAR     ObjectName[260];
} HANDLE_INFO, *PHANDLE_INFO;

typedef struct _HANDLE_LIST_HEADER {
    ULONG Count;
    ULONG TotalSize;
} HANDLE_LIST_HEADER, *PHANDLE_LIST_HEADER;

typedef struct _CLOSE_HANDLE_REQUEST {
    ULONG   ProcessId;
    ULONG64 Handle;
} CLOSE_HANDLE_REQUEST, *PCLOSE_HANDLE_REQUEST;

// ========== 注册表（暂时禁用）==========

typedef struct _REG_PATH_REQUEST {
    WCHAR KeyPath[1024];
} REG_PATH_REQUEST, *PREG_PATH_REQUEST;

typedef struct _REG_VALUE_REQUEST {
    WCHAR KeyPath[1024];
    WCHAR ValueName[256];
} REG_VALUE_REQUEST, *PREG_VALUE_REQUEST;

// ========== 网络连接 ==========

#define CONNECTION_PROTO_TCP  6
#define CONNECTION_PROTO_UDP  17

#define CONNECTION_STATE_CLOSED       1
#define CONNECTION_STATE_LISTEN       2
#define CONNECTION_STATE_SYN_SENT     3
#define CONNECTION_STATE_SYN_RCVD     4
#define CONNECTION_STATE_ESTABLISHED  5
#define CONNECTION_STATE_FIN_WAIT1    6
#define CONNECTION_STATE_FIN_WAIT2    7
#define CONNECTION_STATE_CLOSE_WAIT   8
#define CONNECTION_STATE_CLOSING      9
#define CONNECTION_STATE_LAST_ACK     10
#define CONNECTION_STATE_TIME_WAIT    11
#define CONNECTION_STATE_DELETE_TCB   12

typedef struct _CONNECTION_INFO {
    ULONG   Protocol;
    ULONG   State;
    ULONG   ProcessId;
    UCHAR   LocalAddr[16];
    USHORT  LocalPort;
    UCHAR   RemoteAddr[16];
    USHORT  RemotePort;
    BOOLEAN IsIPv6;
    UCHAR   Padding[1];
} CONNECTION_INFO, *PCONNECTION_INFO;

typedef struct _CONNECTION_LIST_HEADER {
    ULONG Count;
    ULONG TotalSize;
} CONNECTION_LIST_HEADER, *PCONNECTION_LIST_HEADER;

// ========== 进程保护 ==========

#define MAX_PROTECTED_PIDS 64

typedef struct _DRIVER_CONTEXT {
    PDEVICE_OBJECT DeviceObject;
    PVOID          ObCallbackHandle;
    BOOLEAN        ProtectCallbacksReady;
    ULONG          ProtectedPids[MAX_PROTECTED_PIDS];
    UCHAR          OriginalProtection[MAX_PROTECTED_PIDS];
    ULONG          ProtectedPidCount;
    KSPIN_LOCK     ProtectLock;
    FAST_MUTEX     IoctlMutex;
} DRIVER_CONTEXT, *PDRIVER_CONTEXT;

extern DRIVER_CONTEXT g_DriverContext;
